---
title: "Project Proposal"
authors: "Emma Campbell, Gus Compton, Harper Lethin, Maya Gutierez"
format: html
editor: visual
editor_options: 
  message: false
---

# Proposal

```{r}
library(readr)
bob_ross <- read_csv("data/bob_ross_paintings.csv")

```

The dataset we chose is a comprehensive collection of data about the paintings made by Bob Ross on his public television show. Each painting is an observation and the name of each painting is saved. Each paintings season and episode are recorded as well as a list of the colors used. Both the code for each color and the name for each color is documented. Some of the more commonly used colors were saved as variables with an indicator value of 1 or 0 showing whether or not that color was used. The number of unique or uncommon colors were recorded as well. The relative season of the painting was also documented in the dataset.

-   We're using the bob ross dataset (https://github.com/jwilber/Bob_Ross_Paintings/blob/master/data/bob_ross_paintings.csv)\

-   We chose to use this dataset because we're fans of Bob Ross and curious about how systematic he may or may not be in his color use across seasons.

-   The two questions we want to answer are:

    1.  How does bob Ross's color use change across time? Which colors are most popular in each season?
    2.  Which seasons have the most diverse color palettes? Which seasons have the most abundant color palettes?

-   Our plans to answer each question are:

    1.  Make a new variable combining season and episode using the mutate function. Make density plots/barplot for each color using that new time variable as the x-axis.
    2.  Use the summarize function to count the average number of colors in each season, then use Simpson's diversity index to measure how diverse the color palettes are:
        -   Diversity = 1 - sum(n(n-1)/N(N-1)), where: - n = \# times a color is used - N = \# times any color is used
